// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnB6rZOFRlzPLLzuhsV_hM1J4k0130trc',
    appId: '1:91470313678:web:03ead4506082344939b89f',
    messagingSenderId: '91470313678',
    projectId: 'car-ticket-app',
    authDomain: 'car-ticket-app.firebaseapp.com',
    storageBucket: 'car-ticket-app.appspot.com',
    measurementId: 'G-ZNFLCYC93C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXeTIc7AXVD8kReGFX1_erdMo3KCwzGl8',
    appId: '1:91470313678:android:b22c5e5dbf7a398f39b89f',
    messagingSenderId: '91470313678',
    projectId: 'car-ticket-app',
    storageBucket: 'car-ticket-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuIID_EZPjZPbM-OP8ocJ526INqeNUZTk',
    appId: '1:91470313678:ios:0bac0b23ed05f92139b89f',
    messagingSenderId: '91470313678',
    projectId: 'car-ticket-app',
    storageBucket: 'car-ticket-app.appspot.com',
    iosBundleId: 'com.example.carTicket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuIID_EZPjZPbM-OP8ocJ526INqeNUZTk',
    appId: '1:91470313678:ios:0bac0b23ed05f92139b89f',
    messagingSenderId: '91470313678',
    projectId: 'car-ticket-app',
    storageBucket: 'car-ticket-app.appspot.com',
    iosBundleId: 'com.example.carTicket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnB6rZOFRlzPLLzuhsV_hM1J4k0130trc',
    appId: '1:91470313678:web:b7f45a6018d7ccd039b89f',
    messagingSenderId: '91470313678',
    projectId: 'car-ticket-app',
    authDomain: 'car-ticket-app.firebaseapp.com',
    storageBucket: 'car-ticket-app.appspot.com',
    measurementId: 'G-Y03XQP3JZ4',
  );

}